#!/usr/bin/env tsx

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import type { KnownProvider, Model, Api } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, '..', '..');

// Map provider → OpenAI-compatible API type & base URL
// Để thêm provider mới: chỉ cần thêm entry vào đây và thêm type vào KnownProvider
const PROVIDER_MAP: Record<KnownProvider, { api: string; baseUrl: string }> = {
  nvidia: { api: 'openai-completions', baseUrl: 'https://integrate.api.nvidia.com/v1' },
  kilo: { api: 'openai-completions', baseUrl: 'https://api.kilo.ai/v1' },
  opencode: { api: 'openai-completions', baseUrl: 'https://opencode.ai/zen/v1' },
  'opencode-go': { api: 'openai-completions', baseUrl: 'https://opencode.ai/zen/go/v1' },
  // Sau này thêm các provider OpenAI-compatible khác:
  // groq: { api: 'openai-completions', baseUrl: 'https://api.groq.com/openai/v1' },
  // cerebras: { api: 'openai-completions', baseUrl: 'https://api.cerebras.ai/v1' },
  // xai: { api: 'openai-completions', baseUrl: 'https://api.x.ai/v1' },
  // zai: { api: 'openai-completions', baseUrl: 'https://api.z.ai/api/coding/paas/v4' },
  // huggingface: { api: 'openai-completions', baseUrl: 'https://router.huggingface.co/v1' },
  // cloudflare-workers-ai: { api: 'openai-completions', baseUrl: 'https://api.cloudflare.com/client/v4/accounts' },
  // together: { api: 'openai-completions', baseUrl: 'https://api.together.ai/v1' },
  // moonshotai: { api: 'openai-completions', baseUrl: 'https://api.moonshot.ai/v1' },
  // moonshotai-cn: { api: 'openai-completions', baseUrl: 'https://api.moonshot.cn/v1' },
  // xiaomi: { api: 'openai-completions', baseUrl: 'https://api.xiaomimimo.com/v1' },
  // openrouter: { api: 'openai-completions', baseUrl: 'https://openrouter.ai/api/v1' },
  // openai-codex: { api: 'openai-codex-responses', baseUrl: 'https://chatgpt.com/backend-api' },
};

async function generateModels() {
  console.log('Fetching models.dev API...');
  const resp = await fetch('https://models.dev/api.json');
  if (!resp.ok) throw new Error(`Failed to fetch: ${resp.status}`);
  const data = await resp.json();

  const models: Model[] = [];

  // Duyệt tất cả providers trong data
  for (const [providerName, providerData] of Object.entries(data)) {
    const pd = providerData as any;
    if (!pd?.models) continue;

    // Check if provider is known and allowed
    if (!(providerName in PROVIDER_MAP)) continue;
    const { api, baseUrl } = PROVIDER_MAP[providerName as KnownProvider];

    for (const [modelId, m] of Object.entries(pd.models)) {
      const mm = m as any;
      // Chỉ lấy models hỗ trợ tool_call
      if (mm.tool_call !== true) continue;

      models.push({
        id: modelId,
        name: mm.name || modelId,
        api: api as any,
        provider: providerName as KnownProvider,
        baseUrl,
        reasoning: mm.reasoning === true,
        input: mm.modalities?.input?.includes('image') ? ['text', 'image'] : ['text'],
        contextWindow: mm.limit?.context || 4096,
        maxTokens: mm.limit?.output || 4096,
        cost: {
          input: mm.cost?.input || 0,
          output: mm.cost?.output || 0,
          cacheRead: mm.cost?.cache_read || 0,
          cacheWrite: mm.cost?.cache_write || 0,
        },
        // TODO: Bổ sung compat sau nếu cần (ví dụ: NVIDIA, OpenCode special cases)
      } as Model);
    }
  }

  // Group by provider
  const providers: Record<KnownProvider, Record<string, Model>> = {} as any;
  for (const m of models) {
    if (!providers[m.provider]) providers[m.provider] = {};
    providers[m.provider][m.id] = m;
  }

  // Generate TypeScript file
  let output = `// Auto-generated by scripts/generate-models.ts\n// DO NOT EDIT - Run 'npm run generate-models' to update\n\nimport type { Model } from "./types.js";\n\nexport const MODELS = {\n`;

  const sortedProviders = Object.keys(providers).sort() as KnownProvider[];
  for (const provider of sortedProviders) {
    output += `\t${JSON.stringify(provider)}: {\n`;
    const sortedIds = Object.keys(providers[provider]).sort();
    for (const id of sortedIds) {
      const m = providers[provider][id];
      output += `\t\t"${m.id}": {\n`;
      output += `\t\t\tid: "${m.id}",\n`;
      output += `\t\t\tname: "${m.name.replace(/"/g, '\\"')}",\n`;
      output += `\t\t\tapi: "${m.api}",\n`;
      output += `\t\t\tprovider: "${m.provider}",\n`;
      output += `\t\t\tbaseUrl: "${m.baseUrl}",\n`;
      output += `\t\t\treasoning: ${m.reasoning},\n`;
      output += `\t\t\tinput: [${m.input.map(i => `"${i}"`).join(', ')}],\n`;
      output += `\t\t\tcost: { input: ${m.cost.input}, output: ${m.cost.output}, cacheRead: ${m.cost.cacheRead}, cacheWrite: ${m.cost.cacheWrite} },\n`;
      output += `\t\t\tcontextWindow: ${m.contextWindow},\n`;
      output += `\t\t\tmaxTokens: ${m.maxTokens}\n`;
      output += `\t\t} satisfies Model<${JSON.stringify(m.api as Api)}>,\n`;
    }
    output += `\t},\n`;
  }

  output += `} as const;\n`;

  // Write
  const outPath = join(packageRoot, 'llm/models.generated.ts');
  writeFileSync(outPath, output);
  console.log(`Generated ${outPath}`);
  console.log(`Total models: ${models.length}`);
  console.log(`Providers (${sortedProviders.length}): ${sortedProviders.join(', ')}`);
  for (const p of sortedProviders) {
    console.log(`  ${p}: ${Object.keys(providers[p]).length} models`);
  }
}

generateModels().catch(console.error);
